### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by ViTulyankin** [Jack253-png/CAnimation#1]
Really cool mod, but only on 1.18.2

**Comment by Jack253-png** [comment]
I have not many spare time.But I will do it.


| |
郭岫辰
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 10/23/2022 19:31 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [Jack253-png/CAnimation] 1.19 support (Issue #1) |

Really cool mod, but only on 1.18.2
